steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/lautify/lautify-predict', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/lautify/lautify-predict']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'fish-freshness-predict', '--image', 'gcr.io/lautify/lautify-predict', '--region', 'asia-southeast2']
images:
- gcr.io/lautify/lautify-predict